/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "r6_wrapper.go"

#include <stdlib.h>
#include <stdint.h>

// One malloc'd instance per Dissect_Get* call; each has a paired
// Dissect_Free* that releases every string field plus the struct itself.
// "type" is a Go keyword, hence "event_type" below -- keeps the Go and C
// sides using the identical field name instead of cgo's keyword-collision
// renaming rules.

typedef struct {
    char* match_id;
    char* map_name;
    char* game_mode;
    char* game_version;
    char* site;
    int32_t round_number;
    int32_t rounds_per_match;
} DissectHeader;

typedef struct {
    char* name;
    int32_t starting_score;
    int32_t score;
    int32_t won;            // 0/1
    char* win_condition;    // "KilledOpponents"/"SecuredArea"/"DisabledDefuser"/
                             // "DefusedBomb"/"ExtractedHostage"/"Time"/"" if undecided
    char* role;              // "Attack"/"Defense"
} DissectTeam;

typedef struct {
    char* username;
    int32_t team_index;
    char* operator_name;
} DissectPlayer;

typedef struct {
    char* event_type;       // "Kill", "Death", "DefuserPlantComplete", ...
    char* username;
    char* target;
    int32_t headshot;       // -1 = not applicable (source Headshot was nil), else 0/1
    double time_in_seconds;
    char* operator_name;    // actor's operator at the time of this event
} DissectEvent;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern uintptr_t Dissect_Open(char* path);
extern void Dissect_Free(uintptr_t handle);
extern int32_t Dissect_PlayerCount(uintptr_t handle);
extern int32_t Dissect_EventCount(uintptr_t handle);
extern DissectHeader* Dissect_GetHeader(uintptr_t handle);
extern void Dissect_FreeHeader(DissectHeader* h);
extern DissectTeam* Dissect_GetTeam(uintptr_t handle, int32_t index);
extern void Dissect_FreeTeam(DissectTeam* t);
extern DissectPlayer* Dissect_GetPlayer(uintptr_t handle, int32_t index);
extern void Dissect_FreePlayer(DissectPlayer* p);
extern DissectEvent* Dissect_GetEvent(uintptr_t handle, int32_t index);
extern void Dissect_FreeEvent(DissectEvent* e);

#ifdef __cplusplus
}
#endif
