/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "r6_wrapper.go"

#include <stdlib.h>
#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern uintptr_t Dissect_Open(char* path);
extern void Dissect_Free(uintptr_t handle);
extern void Dissect_FreeString(char* s);
extern char* Dissect_MatchID(uintptr_t handle);
extern char* Dissect_Map(uintptr_t handle);
extern char* Dissect_GameMode(uintptr_t handle);
extern char* Dissect_GameVersion(uintptr_t handle);
extern int Dissect_PlayerCount(uintptr_t handle);
extern char* Dissect_PlayerUsername(uintptr_t handle, int index);
extern int Dissect_PlayerTeamIndex(uintptr_t handle, int index);
extern int Dissect_PlayerKills(uintptr_t handle, int index);
extern int Dissect_PlayerDeaths(uintptr_t handle, int index);
extern int Dissect_PlayerAssists(uintptr_t handle, int index);
extern int Dissect_PlayerHeadshots(uintptr_t handle, int index);
extern int Dissect_RoundNumber(uintptr_t handle);
extern int Dissect_RoundsPerMatch(uintptr_t handle);
extern int Dissect_RoundWinningTeamIndex(uintptr_t handle);
extern char* Dissect_ObjectiveSite(uintptr_t handle);
extern int Dissect_EventCount(uintptr_t handle);
extern char* Dissect_EventType(uintptr_t handle, int index);
extern char* Dissect_EventTime(uintptr_t handle, int index);
extern double Dissect_EventTimeInSeconds(uintptr_t handle, int index);
extern char* Dissect_EventUsername(uintptr_t handle, int index);
extern char* Dissect_EventTarget(uintptr_t handle, int index);

#ifdef __cplusplus
}
#endif
